<?php

return array (
  'staff' => 'staff',
  'brandmodels' => 'brandmodels',
  'vehicletypes' => 'vehicletypes',
  'vehicleimages' => 'vehicleimages',
  'zonecoords' => 'zonecoords',
  'program_personnel' => 'program_personnel',
  'run_personnel' => 'run_personnel',
  'attendances' => 'attendances',
  'brands' => 'brands',
  'cache' => 'cache',
  'cache_locks' => 'cache_locks',
  'colors' => 'colors',
  'contracts' => 'contracts',
  'departments' => 'departments',
  'districts' => 'districts',
  'failed_jobs' => 'failed_jobs',
  'functions' => 'functions',
  'jobs' => 'jobs',
  'job_batches' => 'job_batches',
  'migrations' => 'migrations',
  'password_reset_tokens' => 'password_reset_tokens',
  'programs' => 'programs',
  'provinces' => 'provinces',
  'runs' => 'runs',
  'sessions' => 'sessions',
  'shifts' => 'shifts',
  'staff_function' => 'staff_function',
  'users' => 'users',
  'vacations' => 'vacations',
  'vehicles' => 'vehicles',
  'zones' => 'zones',
);
